# numpy-random package
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

## Getting started

In [1]:
import numpy as np

numpy must be imported at the beginning of the notebook and it can be referenced anyway you please, I have gone for a simple np

## Numpy Random
This function allows us to randomly generate an array of numbers

In [2]:
x = np.random.rand(3,4)
print(x)

[[0.05291572 0.75541539 0.25313743 0.10766721]
 [0.01039531 0.93767274 0.45473663 0.18281445]
 [0.98371836 0.05406236 0.67030082 0.43087849]]


There is more than just the one way to display random arrays.

In [3]:
x = np.random.randint(2, size=5)
print(x)

[1 1 0 1 1]


5 random numbers in the arrayare displayed but will not include or be above 2

In [4]:
np.random.bytes(10)

b'\xf4\x8e,Q\x8e\xe1\xa0\xb7m\xe3'

the bytes function displays a random amount bytes in the array

In [5]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([6, 4, 1, 7, 3, 9, 8, 2, 0, 5])

The array is shuffled for a random of 10 numbers.

## ndarray (n-dimensional arrays)
Here we will be using the np.arange function for various methods

The parameters for np.arange are ([start, ]stop, [step, ]dtype=None)

In [6]:
# start step
np.arange(3)

array([0, 1, 2])

Creates a one dimensional array with 3 values starting at zero.

In [7]:
# stop set
np.arange(3,7)

array([3, 4, 5, 6])

Another example of creating an array which starts at 3 and ends at 7 but does not include 7.

In [8]:
# step set
np.arange(10,26,2)

array([10, 12, 14, 16, 18, 20, 22, 24])

This step set takes the values from 10 up to 26 but it accounts for every second value not including 26.

In [9]:
# dtype set 
x = np.arange(5, dtype = float)
print (x)

[0. 1. 2. 3. 4.]


dtype takes the values up to 5 in the array and makes sure they are assigned the correct type e.g, float.